// export const HOST = 'http://localhost:5001/api';
export const HOST = 'https://alethea.abraxasintelligence.com/api';
// override with your own token
// export const TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIwNzY0NDc3Yi05MTg3LTQyYmUtYjI2MC1mOGExMTlhMmRlMDciLCJzZWNyZXQiOiJlM2U2YzZhMy1hODBhLTQwYzMtOTI0OS1hOTI5NTkwNzFjNDIiLCJpYXQiOjE1MjI0MjkzNzMsImV4cCI6MTUyMzAzNDE3M30.RVyMCGcn8hbxBZv2VxDVv6gDkJlWfpfBs0huMisKBz0';
export const TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJjMDc4ODU5NC05YjExLTQ0MmQtOGJhMi1kODI5OTFkY2M3ZmEiLCJzZWNyZXQiOiIzNGUwNWY5ZS0xYzczLTRiMWUtYjY4OC1iNWI1YTY0MmE2N2YiLCJpYXQiOjE1MjI4NjY4MjIsImV4cCI6MTUyMzQ3MTYyMn0.q7kr4DXK0xg-GvedrvFWZUXMbzQypgdeqIa9JYyj0fQ'